"""
Module to generate Darktable .dtstyle files programmatically.
Currently supports:
- Exposure module (exposure bias)
"""

import struct
import base64
import logging
from pathlib import Path

# Headers/Footers for .dtstyle XML
DTSTYLE_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<darktable_style version="1.0">
  <info>
    <name>{name}</name>
    <description>{description}</description>
  </info>
"""

DTSTYLE_FOOTER = """</darktable_style>"""

class DarktableStyleGenerator:
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _float_to_hex(self, val: float) -> str:
        """Pack a float into little-endian hex string."""
        return "".join(f"{b:02x}" for b in struct.pack("<f", float(val)))

    def _int_to_hex(self, val: int) -> str:
        """Pack an int into little-endian hex string."""
        return "".join(f"{b:02x}" for b in struct.pack("<i", int(val)))

    def _generate_exposure_blob(self, exposure_ev: float) -> str:
        """
        Generates the binary params blob for the 'exposure' module.
        Based on reverse-engineering or common struct layout:
        int mode;           // 0 = MANUAL
        float black_level;  // 0.0
        float exposure;     // target EV
        float deflicker;    // default (usually ignored in manual mode)
        """
        mode = 0      # manual
        black = 0.0
        exposure = exposure_ev
        deflicker = 0.0 # meaningless for manual?
        
        # Packing: int, float, float, float -> 16 bytes total
        # Using little-endian (<) standard for x86/linux
        blob = struct.pack("<ifff", mode, black, exposure, deflicker)
        return "".join(f"{b:02x}" for b in blob)

    def generate_style(self, name: str, params: dict) -> Path:
        """
        Generates a .dtstyle file.
        
        Args:
            name: Style name (and filename).
            params: Dictionary of supported adjustments.
                    e.g. {"exposure": 1.5, "notes": "..."}
        
        Returns:
            Path to the generated file.
        """
        sanitized_name = "".join(x for x in name if x.isalnum() or x in " _-").strip()
        filename = f"{sanitized_name}.dtstyle"
        file_path = self.output_dir / filename
        
        content = [DTSTYLE_HEADER.format(name=name, description="Generated by MCP Darktable Assistant")]
        
        # 1. Exposure
        if "exposure" in params:
            ev = float(params["exposure"])
            # Hardcoded blendop_params for 'normal' blend
            blendop = "gz11eJxjYGBgkGAAgRNODESDBnsIHll8ANNSGQM=" 
            params_hex = self._generate_exposure_blob(ev)
            
            # XML for exposure module
            # Using blendop_version 11 (common in modern DT)
            # multi_priority 0 (default)
            module_xml = f"""  <style_item>
    <num>0</num>
    <module>exposure</module>
    <op>exposure</op>
    <enabled>1</enabled>
    <blendop_params>{blendop}</blendop_params>
    <blendop_version>11</blendop_version>
    <multi_priority>0</multi_priority>
    <multi_name></multi_name>
    <params>{params_hex}</params>
  </style_item>"""
            content.append(module_xml)

        content.append(DTSTYLE_FOOTER)
        
        file_path.write_text("\n".join(content), encoding="utf-8")
        logging.info(f"[StyleGenerator] Style created: {file_path}")
        return file_path
