import struct
import base64
import datetime

# Minimal header for a .dtstyle file
DTSTYLE_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<darktable_style version="1.0">
  <info>
    <name>{name}</name>
    <description>{description}</description>
  </info>
"""

DTSTYLE_FOOTER = """</darktable_style>"""

def float_to_hex(f):
    """Converts a float to the specific hex string format often used in XMP/XML params."""
    # Darktable seems to use standard IEEE 754 float representation in some places, 
    # but strictly speaking, in .dtstyle XML, many modules use `params="..."` which is a hex blob.
    # For `exposure`, the param struct is basically `float mode, float black, float exposure`.
    # Let's try raw C struct packing.
    return "".join(f"{b:02x}" for b in struct.pack("f", float(f)))

def generate_exposure_block(exposure_ev: float):
    # Exposure module params (v6):
    # mode (int), black_level (float), exposure (float), deflicker_percentile (float), ...
    # Wait, reverse engineering struct is hard.
    # ALTERNATIVE: Use operations that map to simpler modules or check defaults.
    
    # If we can't easily generate the binary blob, we might fail.
    # Let's hope standard XML structure works or we use a known-good blob and patch the exposure float.
    # Known blob for Exposure +0.0:
    # 0000000000000000000000000000803f
    # mode(0), black(0.0), exposure(0.0), deflicker(1.0)?
    
    # Struct:
    # int mode;         // 4 bytes
    # float black;      // 4 bytes
    # float exposure;   // 4 bytes
    # float deflicker;  // 4 bytes
    
    mode = 0  # MANUAL
    black = 0.0
    exposure = exposure_ev
    deflicker = 50.0 # default?
    
    # Pack: i f f f
    # But wait, deflicker might be irrelevant for manual mode.
    # Let's try packing:
    blob = struct.pack("ifff", mode, black, exposure, deflicker)
    return "".join(f"{b:02x}" for b in blob)

def create_style_xml(style_name, exposure=0.0):
    # Only supporting exposure for POC
    content = [DTSTYLE_HEADER.format(name=style_name, description="Generated by MCP")]
    
    # Exposure Module
    # We need operation, enabled, modversion, params, etc.
    # Assuming modversion 6 for modern DT.
    params_hex = generate_exposure_block(exposure)
    
    # Note: "num" is order index.
    module_xml = f"""  <style_item>
    <num>0</num>
    <module>exposure</module>
    <op>exposure</op>
    <enabled>1</enabled>
    <blendop_params>gz11eJxjYGBgkGAAgRNODESDBnsIHll8ANNSGQM=</blendop_params>
    <blendop_version>11</blendop_version>
    <multi_priority>0</multi_priority>
    <multi_name></multi_name>
    <params>{params_hex}</params>
  </style_item>"""
    
    content.append(module_xml)
    content.append(DTSTYLE_FOOTER)
    return "\n".join(content)

if __name__ == "__main__":
    # Test
    print(create_style_xml("TestStyle", 1.5))
